export const USER_TYPE = {
  SELLER: "SELLER",
  BUYER: "BUYER",
};

export const PROPERTY_TYPE = {
  HOUSE: "HOUSE",
  VILLA: "VILLA",
  LOT: "LOT",
  FLAT: "FLAT",
  APARTMENT: "APARTMENT",
  BUNGALOW: "BUNGALOW",
  "FARM HOUSE": "FARM HOUSE",
  "PENT HOUSE": "PENT HOUSE",
  "COUNTRY HOME": "COUNTRY HOME",
  FARM_HOUSE: "FARM_HOUSE",
  PENT_HOUSE: "PENT_HOUSE",
  COUNTRY_HOME: "COUNTRY_HOME",
  INDEPENDENT_HOUSE: "HOUSE",
  CHATEAU: "CHATEAU",
  CABIN: "CABIN",
  PROJECT: "PROJECT",
  COMMERCIAL: "COMMERCIAL",
  COMMERCIAL_PROPERTIES: "COMMERCIAL",
  PG: "PG",
};

export const LISTING_TYPE = {
  SALE: "SALE",
  RENT: "RENT",
  LEASE: "LEASE",
};

export const PROPERTY_CONDITION = {
  OK: "OK",
  GOOD: "GOOD",
  VERY_GOOD: "VERY GOOD",
  AVERAGE: "AVERAGE",
  BAD: "BAD",
};

export const PROPERTY_STATUS = {
  IN_REVIEW: "IN REVIEW",
  REJECTED: "REJECTED",
  APPROVED: "APPROVED",
  NOT_FOR_SALE: "NOT FOR SALE",
  NOT_FOR_RENT: "NOT FOR RENT",
  SOLD: "SOLD",
};

export const ALL_CITIES = [
  "HYDERABAD",
  "VISHAKAPATNAM",
  "VIJAYAWADA",
  "AMALAPURAM",
  "BANGALORE",
  "PUNE",
];

export const LOCALITIES = {
  HYDERABAD: [],
  VISHAKAPATNAM: [],
  VIJAYAWADA: [],
  AMALAPURAM: [],
  BANGALORE: [],
  PUNE: [],
};
