export const USER_TYPE = {
  SELLER: "SELLER",
  BUYER: "BUYER",
};

export const PROPERTY_TYPE = {
  HOUSE: "HOUSE",
  VILLA: "VILLA",
  LOT: "LOT",
  APARTMENT: "APARTMENT",
  BUNGALOW: "BUNGALOW",
  FARM_HOUSE: "FARM HOUSE",
  PENT_HOUSE: "PENT HOUSE",
  COUNTRY_HOME: "COUNTRY HOME",
  CHATEAU: "CHATEAU",
  CABIN: "CABIN",
  PROJECT: "PROJECT",
  COMMERCIAL: "COMMERCIAL",
};

export const LISTING_TYPE = {
  SALE: "SALE",
  RENT: "RENT",
  LEASE: "LEASE",
};

export const PROPERTY_CONDITION = {
  OK: "OK",
  GOOD: "GOOD",
  VERY_GOOD: "VERY GOOD",
  AVERAGE: "AVERAGE",
  BAD: "BAD",
};

export const PROPERTY_STATUS = {
  IN_REVIEW: "IN REVIEW",
  REJECTED: "REJECTED",
  APPROVED: "APPROVED",
  NOT_FOR_SALE: "NOT FOR SALE",
  NOT_FOR_RENT: "NOT FOR RENT",
  SOLD: "SOLD",
};
